version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily


  - package-ecosystem: maven
    directory: /m2e-maven-runtime/org.eclipse.m2e.archetype.common
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /m2e-maven-runtime/org.eclipse.m2e.maven.runtime
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /m2e-maven-runtime
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /m2e-parent
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /org.eclipse.m2e.repository
    schedule:
      interval: daily
